#!bin/bash
private static void readFile(){ 
String txt null; 
try { 
BufferedReader bufferedReader = new BufferedReader(new FileReader("/uploads/TMA.txt")); 
while((txt = bufferedReader.readLine()) != null) { 
System.out.println(txt); 
} bufferedReader.close(); 
} catch(FileNotFoundException ex) { 
System.out.println("Unable to read...");
} catch(IOException ex) { 
    System.out.println("Unable to read...");
}
 }
